begin;

create table if not exists public.officers (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.officers enable row level security;
revoke all on table public.officers from anon;
revoke all on table public.officers from authenticated;
grant select on table public.officers to authenticated;

drop policy if exists "Officers can verify membership" on public.officers;
create policy "Officers can verify membership"
on public.officers for select
to authenticated
using (user_id = (select auth.uid()));

-- Existing Auth users were created as board accounts. Future Auth signups are
-- not automatically added here and therefore receive no officer permissions.
insert into public.officers (user_id)
select id from auth.users
on conflict (user_id) do nothing;

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 100),
  email text not null check (char_length(email) between 3 and 254),
  message text not null check (char_length(message) between 1 and 2000),
  page_path text check (page_path is null or char_length(page_path) <= 200),
  status text not null default 'new' check (status in ('new', 'read', 'archived')),
  created_at timestamptz not null default now(),
  read_at timestamptz
);

alter table public.contact_messages enable row level security;
revoke all on table public.contact_messages from anon;
revoke all on table public.contact_messages from authenticated;
grant insert on table public.contact_messages to anon, authenticated;
grant select, update on table public.contact_messages to authenticated;
grant usage, select on sequence public.contact_messages_id_seq to anon, authenticated;

drop policy if exists "Public can submit contact messages" on public.contact_messages;
create policy "Public can submit contact messages"
on public.contact_messages for insert
to anon, authenticated
with check (status = 'new' and read_at is null);

drop policy if exists "Officers can read contact messages" on public.contact_messages;
create policy "Officers can read contact messages"
on public.contact_messages for select
to authenticated
using (exists (
  select 1 from public.officers
  where officers.user_id = (select auth.uid())
));

drop policy if exists "Officers can update contact messages" on public.contact_messages;
create policy "Officers can update contact messages"
on public.contact_messages for update
to authenticated
using (exists (
  select 1 from public.officers
  where officers.user_id = (select auth.uid())
))
with check (exists (
  select 1 from public.officers
  where officers.user_id = (select auth.uid())
));

-- Let the public read privacy-safe sessions and let officers maintain them.
revoke all on table public.public_tutoring_sessions from anon;
revoke all on table public.public_tutoring_sessions from authenticated;
grant select on table public.public_tutoring_sessions to anon;
grant select, insert, update, delete on table public.public_tutoring_sessions to authenticated;
grant usage, select on sequence public.public_tutoring_sessions_id_seq to authenticated;

drop policy if exists "Officers can manage tutoring sessions" on public.public_tutoring_sessions;
create policy "Officers can manage tutoring sessions"
on public.public_tutoring_sessions for all
to authenticated
using (exists (
  select 1 from public.officers
  where officers.user_id = (select auth.uid())
))
with check (exists (
  select 1 from public.officers
  where officers.user_id = (select auth.uid())
));

create or replace function public.sync_public_tutoring_session()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if new.status = 'confirmed' and new.confirmed_start is not null and new.confirmed_end is not null then
    insert into public.public_tutoring_sessions
      (request_id, title, math_class, starts_at, ends_at, updated_at)
    values
      (new.id, 'Math NHS Tutoring', new.math_class, new.confirmed_start, new.confirmed_end, now())
    on conflict (request_id) do update
      set title = excluded.title,
          math_class = excluded.math_class,
          starts_at = excluded.starts_at,
          ends_at = excluded.ends_at,
          updated_at = now();
  elsif tg_op = 'UPDATE' then
    delete from public.public_tutoring_sessions where request_id = new.id;
  end if;
  return new;
end;
$$;

-- Restrict private tutoring requests to registered officers.
drop policy if exists "Officers can read tutoring requests" on public.tutoring_requests;
create policy "Officers can read tutoring requests"
on public.tutoring_requests for select
to authenticated
using (exists (
  select 1 from public.officers
  where officers.user_id = (select auth.uid())
));

drop policy if exists "Officers can update tutoring requests" on public.tutoring_requests;
create policy "Officers can update tutoring requests"
on public.tutoring_requests for update
to authenticated
using (exists (
  select 1 from public.officers
  where officers.user_id = (select auth.uid())
))
with check (exists (
  select 1 from public.officers
  where officers.user_id = (select auth.uid())
));

-- Meeting access and Slides remain public to read, but only officers can edit.
drop policy if exists "Allow authenticated read" on public.current_meeting_access;
drop policy if exists "Allow authenticated insert" on public.current_meeting_access;
drop policy if exists "Allow authenticated update" on public.current_meeting_access;
create policy "Officers can read meeting access"
on public.current_meeting_access for select to authenticated
using (exists (select 1 from public.officers where officers.user_id = (select auth.uid())));
create policy "Officers can insert meeting access"
on public.current_meeting_access for insert to authenticated
with check (id = 1 and exists (select 1 from public.officers where officers.user_id = (select auth.uid())));
create policy "Officers can update meeting access"
on public.current_meeting_access for update to authenticated
using (id = 1 and exists (select 1 from public.officers where officers.user_id = (select auth.uid())))
with check (id = 1 and exists (select 1 from public.officers where officers.user_id = (select auth.uid())));

drop policy if exists "Allow authenticated read" on public.current_slides;
drop policy if exists "Allow authenticated insert" on public.current_slides;
drop policy if exists "Allow authenticated update" on public.current_slides;
create policy "Officers can read slides"
on public.current_slides for select to authenticated
using (exists (select 1 from public.officers where officers.user_id = (select auth.uid())));
create policy "Officers can insert slides"
on public.current_slides for insert to authenticated
with check (id = 1 and exists (select 1 from public.officers where officers.user_id = (select auth.uid())));
create policy "Officers can update slides"
on public.current_slides for update to authenticated
using (id = 1 and exists (select 1 from public.officers where officers.user_id = (select auth.uid())))
with check (id = 1 and exists (select 1 from public.officers where officers.user_id = (select auth.uid())));

-- Storage policies for the active meeting-qr bucket.
drop policy if exists "Officers can read meeting QR objects" on storage.objects;
drop policy if exists "Officers can replace meeting QR objects" on storage.objects;
drop policy if exists "Officers can upload meeting QR" on storage.objects;
create policy "Officers can read meeting QR objects"
on storage.objects for select to authenticated
using (bucket_id = 'meeting-qr' and exists (
  select 1 from public.officers where officers.user_id = (select auth.uid())
));
create policy "Officers can replace meeting QR objects"
on storage.objects for update to authenticated
using (bucket_id = 'meeting-qr' and exists (
  select 1 from public.officers where officers.user_id = (select auth.uid())
))
with check (bucket_id = 'meeting-qr' and exists (
  select 1 from public.officers where officers.user_id = (select auth.uid())
));
create policy "Officers can upload meeting QR"
on storage.objects for insert to authenticated
with check (bucket_id = 'meeting-qr' and exists (
  select 1 from public.officers where officers.user_id = (select auth.uid())
));

commit;
